import type { ColumnDef, TableDef, RelationshipDef, BuildOptions, DataType } from './types';
import { topologicalSort } from './topo-sort';

const PG_TYPE_MAP: Record<DataType, string> = {
  VARCHAR: 'VARCHAR(255)',
  TEXT: 'TEXT',
  INTEGER: 'INTEGER',
  BIGINT: 'BIGINT',
  DECIMAL: 'DECIMAL(10,2)',
  BOOLEAN: 'BOOLEAN',
  TIMESTAMP: 'TIMESTAMPTZ',
  DATE: 'DATE',
  UUID: 'UUID',
  SERIAL: 'SERIAL',
  JSON: 'JSONB',
};

function q(id: string): string {
  return `"${id}"`;
}

function trunc(name: string, max = 63): string {
  return name.length <= max ? name : name.slice(0, max);
}

function pgDefault(col: ColumnDef): string | null {
  if (col.defaultValue) return formatLiteral(col.defaultValue);
  if (col.dataType === 'UUID' && col.isPrimaryKey) return 'gen_random_uuid()';
  if (col.dataType === 'TIMESTAMP') return 'NOW()';
  if (col.dataType === 'SERIAL') return null; // sequence handles it
  return null;
}

function formatLiteral(val: string): string {
  if (/^-?\d+(\.\d+)?$/.test(val)) return val;
  if (/^(true|false|null)$/i.test(val)) return val.toUpperCase();
  if (/[\(\)\s]/.test(val)) return val; // already a SQL expression
  return `'${val.replace(/'/g, "''")}'`;
}

function buildColumn(col: ColumnDef): string {
  if (col.dataType === 'SERIAL') {
    const notNull = ' NOT NULL';
    return `  ${q(col.name)} SERIAL${notNull}`;
  }

  const type = PG_TYPE_MAP[col.dataType] ?? 'TEXT';
  const notNull = col.isPrimaryKey || !col.isNullable ? ' NOT NULL' : '';
  const def = pgDefault(col);
  const defaultClause = def ? ` DEFAULT ${def}` : '';
  return `  ${q(col.name)} ${type}${notNull}${defaultClause}`;
}

function buildTableConstraints(table: TableDef): string[] {
  const constraints: string[] = [];
  const pkCols = table.columns.filter((c) => c.isPrimaryKey);
  if (pkCols.length > 0) {
    const cols = pkCols.map((c) => q(c.name)).join(', ');
    constraints.push(`  CONSTRAINT ${q(trunc(`pk_${table.name}`))} PRIMARY KEY (${cols})`);
  }
  for (const col of table.columns) {
    if (col.isUnique && !col.isPrimaryKey) {
      constraints.push(`  CONSTRAINT ${q(trunc(`uq_${table.name}_${col.name}`))} UNIQUE (${q(col.name)})`);
    }
  }
  return constraints;
}

function buildTable(table: TableDef, ifNotExists: boolean): string {
  const defs = [...table.columns.map(buildColumn), ...buildTableConstraints(table)];
  const keyword = ifNotExists ? 'IF NOT EXISTS ' : '';
  return `CREATE TABLE ${keyword}${q(table.name)} (\n${defs.join(',\n')}\n);`;
}

function buildFkConstraint(
  tables: Map<string, TableDef>,
  rel: RelationshipDef,
): string | null {
  const srcTable = tables.get(rel.sourceTableId);
  const tgtTable = tables.get(rel.targetTableId);
  if (!srcTable || !tgtTable) return null;

  const srcCol = srcTable.columns.find((c) => c.id === rel.sourceColumnId);
  const tgtCol = tgtTable.columns.find((c) => c.id === rel.targetColumnId);
  if (!srcCol || !tgtCol) return null;

  const constraintName = trunc(`fk_${srcTable.name}_${srcCol.name}`);
  const onDelete = rel.onDelete === 'NO_ACTION' ? 'NO ACTION' : rel.onDelete.replace('_', ' ');

  return (
    `ALTER TABLE ${q(srcTable.name)}\n` +
    `  ADD CONSTRAINT ${q(constraintName)}\n` +
    `  FOREIGN KEY (${q(srcCol.name)}) REFERENCES ${q(tgtTable.name)} (${q(tgtCol.name)})\n` +
    `  ON DELETE ${onDelete};`
  );
}

function buildIndex(tables: Map<string, TableDef>, rel: RelationshipDef): string | null {
  const srcTable = tables.get(rel.sourceTableId);
  if (!srcTable) return null;
  const srcCol = srcTable.columns.find((c) => c.id === rel.sourceColumnId);
  if (!srcCol) return null;

  const indexName = trunc(`idx_${srcTable.name}_${srcCol.name}`);
  return `CREATE INDEX IF NOT EXISTS ${q(indexName)} ON ${q(srcTable.name)} (${q(srcCol.name)});`;
}

export function buildPostgresSQL(
  tables: TableDef[],
  relationships: RelationshipDef[],
  options: BuildOptions,
): string {
  const sorted = topologicalSort(tables, relationships);
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const ifNotExists = options.mode === 'safe';
  const parts: string[] = [
    `-- Generated by Relatrix Migration Engine`,
    `-- Schema: ${options.schemaName}`,
    `-- Dialect: PostgreSQL`,
    `-- Mode: ${options.mode}`,
    `-- Generated at: ${new Date().toISOString()}`,
  ];

  // DROP phase (replace mode — drop in reverse order)
  if (options.mode === 'replace') {
    parts.push('');
    parts.push('-- ── Drop existing tables ──────────────────────────────────────────────────');
    for (const table of [...sorted].reverse()) {
      parts.push(`DROP TABLE IF EXISTS ${q(table.name)} CASCADE;`);
    }
  }

  // CREATE phase
  parts.push('');
  parts.push('-- ── Table definitions ─────────────────────────────────────────────────────');
  for (const table of sorted) {
    parts.push('');
    parts.push(`-- ${table.displayName}`);
    parts.push(buildTable(table, ifNotExists));
  }

  // FK constraints (always via ALTER TABLE to handle any dependency order)
  const fkStatements = relationships
    .map((r) => buildFkConstraint(tableMap, r))
    .filter((s): s is string => s !== null);

  if (fkStatements.length > 0) {
    parts.push('');
    parts.push('-- ── Foreign key constraints ───────────────────────────────────────────────');
    parts.push('');
    parts.push(...fkStatements);
  }

  // Indexes for FK columns
  const indexStatements = relationships
    .map((r) => buildIndex(tableMap, r))
    .filter((s): s is string => s !== null);

  // Deduplicate (multiple relationships may reference the same column)
  const uniqueIndexes = [...new Set(indexStatements)];
  if (uniqueIndexes.length > 0) {
    parts.push('');
    parts.push('-- ── Indexes ───────────────────────────────────────────────────────────────');
    parts.push('');
    parts.push(...uniqueIndexes);
  }

  return parts.join('\n');
}
